---
- hosts: win2016-compute
  any_errors_fatal: true
  vars_files: 
    - zuul-params.yaml

  tasks:
    - name: Include variables from group_vars/windows
      include_vars: "group_vars/windows"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}.yaml"
      failed_when: False
      tags: always

    - name: Include variables from job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml
      include_vars: "job_vars/{{ zuul_project | basename }}-{{ job_type }}.yaml"
      when: job_type is defined
      failed_when: False
      tags: always

    # Run sanity checks as early as possible
    - include: tasks/windows/sanity-checks.yaml
    - name: Install FS-iSCSITarget-Server
      win_feature:
        name: FS-iSCSITarget-Server
        state: present
      when: job_type == "iscsi" and job_type is defined

    - include: build-win2016.yaml
